# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-15 16:39


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListURL',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('ip_add', models.CharField(max_length=30)),
                ('notif_type', models.CharField(max_length=200, null=True)),
                ('data', models.TextField()),
            ],
        ),
    ]
