# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-14 11:21


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listurl',
            name='paste_url',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
