# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-10 18:07


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0002_listurl_paste_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listurl',
            old_name='datetime',
            new_name='current_time',
        ),
    ]
