# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-19 16:34


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0003_auto_20180710_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifAuth',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('client', models.CharField(max_length=20, null=True)),
                ('user', models.CharField(max_length=30)),
                ('passwd', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(max_length=100)),
            ],
        ),
    ]
