# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-19 16:45


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0004_notifauth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotifAuth',
        ),
    ]
