# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-19 16:57


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0006_notifauth'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='notifauth',
            name='token',
        ),
        migrations.AddField(
            model_name='authtoken',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notifier.NotifAuth'),
        ),
    ]
