# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-01 11:03


import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0007_auto_20181119_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listurl',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
