# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-01 11:56


import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0008_auto_20190401_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifData',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_time', models.DateTimeField(auto_now_add=True)),
                ('ip_add', models.CharField(max_length=30)),
                ('notif_type', models.CharField(max_length=200, null=True)),
                ('paste_url', models.CharField(max_length=30, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
