# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-01 11:56


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0009_notifdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listurl',
            name='data',
            field=models.TextField(),
        ),
    ]
