# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-01 12:06


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0010_auto_20190401_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifdata',
            old_name='current_time',
            new_name='created_on',
        ),
    ]
