# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-01 16:23


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0011_auto_20190401_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifdata',
            name='created_on',
            field=models.DateTimeField(blank=True),
        ),
    ]
