# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-01 16:28


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0012_auto_20190401_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifdata',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
