# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-16 16:36


import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0013_auto_20190401_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifURL',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url_pattern', models.URLField(max_length=30)),
                ('response', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ListURL',
        ),
    ]
