# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-21 11:34


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0014_auto_20190516_1636'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotifURL',
        ),
    ]
