# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-21 11:35


import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0015_delete_notifurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifURL',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url_pattern', models.URLField(max_length=30, unique=True)),
                ('response', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_by', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
