# Generated by Django 3.2 on 2025-07-18 16:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0016_notifurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddressNotifData',
            fields=[
                ('ip_address', models.GenericIPAddressField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='notifdata',
            name='esr_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notifdata',
            name='headers',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notifdata',
            name='notif_type',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ElevatorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_add', models.GenericIPAddressField()),
                ('elevator_id', models.IntegerField()),
                ('floor_id', models.IntegerField()),
            ],
            options={
                'unique_together': {('ip_add', 'elevator_id')},
            },
        ),
        migrations.AlterField(
            model_name='notifdata',
            name='ip_add',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifier.ipaddressnotifdata'),
        ),
    ]
